sudo: required
services:
    - docker

before_install:
    - docker build -t tkhara/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tkhara/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-279014245023"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY